#DATABASE OF FAIL2BAN 

drop database F2B_LOGS_DB;
CREATE DATABASE IF NOT EXISTS F2B_LOGS_DB;

USE F2B_LOGS_DB;


CREATE TABLE LOGS(
	LOG_MAC VARCHAR(30),
	LOG_DATE DATE,
	LOG_TIME TIME(3),
	LOG_RESOURCE VARCHAR(50),
	LOG_PID VARCHAR(20),
	LOG_STATUS VARCHAR(50),
	LOG_ACTION VARCHAR(100),
	CONSTRAINT LINE PRIMARY KEY (LOG_MAC, LOG_DATE, LOG_TIME, LOG_ACTION) 
)







