#DATABASE OF FAIL2BAN 

drop database F2B_LOGS_DB;
CREATE DATABASE IF NOT EXISTS F2B_LOGS_DB;

USE F2B_LOGS_DB;


CREATE TABLE LOGS(
	LOG_MAC VARCHAR(30),
	LOG_DATETIME TIMESTAMP,
	LOG_RESOURCE VARCHAR(50),
	LOG_PID VARCHAR(20),
	LOG_STATUS VARCHAR(50),
	LOG_ACTION VARCHAR(150),
	CONSTRAINT LINE PRIMARY KEY (LOG_MAC, LOG_DATETIME, LOG_ACTION) 
)







